services:
    clash82.ezstudio_tips_block:
        class: Clash82\EzPlatformStudioTipsBlockBundle\Block\TipsBlock
        arguments:
            - '@ezpublish.api.service.content'
            - '@ezpublish.api.service.search'
        tags:
            - name: landing_page_field_type.block_type
              alias: tips

    clash82.ezstudio_tips_block.installer:
        class: Clash82\EzPlatformStudioTipsBlockBundle\Installer\ContentTypeInstaller
        arguments:
            - '@ezpublish.api.repository'
            - '@ezpublish.api.service.user'
            - '@ezpublish.api.service.content_type'
        tags:
            - name: console.command
